# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pycoordinate
else:
    import _pycoordinate

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Coordinate(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycoordinate.Coordinate_swiginit(self, _pycoordinate.new_Coordinate(*args))
    __swig_destroy__ = _pycoordinate.delete_Coordinate

    def __eq__(self, coordinate):
        return _pycoordinate.Coordinate___eq__(self, coordinate)

    def x(self, *args):
        return _pycoordinate.Coordinate_x(self, *args)

    def y(self, *args):
        return _pycoordinate.Coordinate_y(self, *args)

    def isValid(self):
        return _pycoordinate.Coordinate_isValid(self)

    @staticmethod
    def calcDistance(coordinate1, coordinate2):
        return _pycoordinate.Coordinate_calcDistance(coordinate1, coordinate2)

    @staticmethod
    def calcBearing(origin, destination):
        return _pycoordinate.Coordinate_calcBearing(origin, destination)

    @staticmethod
    def calcDestination(coordinate, distance, bearing):
        return _pycoordinate.Coordinate_calcDestination(coordinate, distance, bearing)

# Register Coordinate in _pycoordinate:
_pycoordinate.Coordinate_swigregister(Coordinate)
cvar = _pycoordinate.cvar
DBL_NAN = cvar.DBL_NAN


